Repository xeoza/TDT-iOS, pull requests merged in 2020-02, with the labels that each got.

#1 Initialize an iOS app
  Podfile
  README.md
  TDT-project.xcodeproj/project.pbxproj
  TDT-project.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  TDT-project.xcodeproj/xcshareddata/xcschemes/TDT-project.xcscheme
  TDT-project.xcworkspace/contents.xcworkspacedata
  TDT-project/AppDelegate.swift
  TDT-project/Assets.xcassets/Contents.json
  TDT-project/AuthenticationControllers/Onboarding/OnboardingContainerView.swift
  TDT-project/AuthenticationControllers/Onboarding/OnboardingController.swift
  TDT-project/GeneralTabBarController.swift
  TDT-project/Info.plist
  TDT-project/TDT-project.entitlements
Labels: enhancement, good first issue

#3 Added Travis_CI config file
  .travis.yml
Labels: enhancement

#2 Added Firebase
  GoogleService-Info.plist
  Podfile
  Podfile.lock
  TDT-project.xcodeproj/project.pbxproj
  TDT-project/AppDelegate.swift
Labels: enhancement

#4 Update README.md
  README.md
Labels: documentation

#5 added auto-increment application version and bundle build status
  .travis.yml
  README.md
  TDT-project.xcodeproj/project.pbxproj
  TDT-project/Info.plist
Labels: enhancement

#6 added codecov report
  .travis.yml
  README.md
  TDT-project.xcodeproj/xcshareddata/xcschemes/TDT-project.xcscheme
Labels: documentation

#7 update auto-increment in .travis.yml
  .travis.yml
Labels: bug
